name: Deploy Nodepad

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Environement
        run: |
          set -e
          cd /root/nodepad

          export DATABASE_URL="${{ secrets.DATABASE_URL }}"
          export NODE_ENV=production

      - name: pull changes and update dependencies
        run: |
          git reset --hard origin/main
          git pull
          npm ci
      
      - name: Run Migrations
        run: |
          npx prisma migrate deploy
          npx prisma generate
      - name: Build and Restart
        run: |
          npm run build
          pm2 reload nodepad --update-env