name: Deploy Nodepad

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy
        run: |
          set -e
          cd /nodepad

          export DATABASE_URL="${{ secrets.DATABASE_URL }}"
          export NODE_ENV=production

          git reset --hard origin/main
          git pull
          npm ci
          npx prisma migrate deploy
          npx prisma generate
          npm run build
          pm2 reload nodepad --update-env